/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeedDatingRouteRouteImport } from './routes/speed-dating/route'
import { Route as SignupRouteRouteImport } from './routes/signup/route'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedOnboardingRouteRouteImport } from './routes/_authenticated/onboarding/route'
import { Route as AuthenticatedChatRouteRouteImport } from './routes/_authenticated/chat/route'
import { Route as AuthenticatedPersonasQuizRouteRouteImport } from './routes/_authenticated/personas/quiz/route'
import { Route as AuthenticatedPersonasMeRouteRouteImport } from './routes/_authenticated/personas/me/route'
import { Route as AuthenticatedPersonasCreateRouteRouteImport } from './routes/_authenticated/personas/create/route'
import { Route as AuthenticatedOnboardingSpeedDatingRouteRouteImport } from './routes/_authenticated/onboarding/speed-dating/route'
import { Route as AuthenticatedOnboardingReviewRouteRouteImport } from './routes/_authenticated/onboarding/review/route'
import { Route as AuthenticatedOnboardingQuizRouteRouteImport } from './routes/_authenticated/onboarding/quiz/route'
import { Route as AuthenticatedOnboardingProfileRouteRouteImport } from './routes/_authenticated/onboarding/profile/route'

const SpeedDatingRouteRoute = SpeedDatingRouteRouteImport.update({
  id: '/speed-dating',
  path: '/speed-dating',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRouteRoute = SignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRouteRoute =
  AuthenticatedOnboardingRouteRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatRouteRoute = AuthenticatedChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonasQuizRouteRoute =
  AuthenticatedPersonasQuizRouteRouteImport.update({
    id: '/personas/quiz',
    path: '/personas/quiz',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPersonasMeRouteRoute =
  AuthenticatedPersonasMeRouteRouteImport.update({
    id: '/personas/me',
    path: '/personas/me',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPersonasCreateRouteRoute =
  AuthenticatedPersonasCreateRouteRouteImport.update({
    id: '/personas/create',
    path: '/personas/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingSpeedDatingRouteRoute =
  AuthenticatedOnboardingSpeedDatingRouteRouteImport.update({
    id: '/speed-dating',
    path: '/speed-dating',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingReviewRouteRoute =
  AuthenticatedOnboardingReviewRouteRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingQuizRouteRoute =
  AuthenticatedOnboardingQuizRouteRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingProfileRouteRoute =
  AuthenticatedOnboardingProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/login': typeof LoginRouteRoute
  '/register': typeof RegisterRouteRoute
  '/signup': typeof SignupRouteRoute
  '/speed-dating': typeof SpeedDatingRouteRoute
  '/chat': typeof AuthenticatedChatRouteRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRoute
  '/onboarding/profile': typeof AuthenticatedOnboardingProfileRouteRoute
  '/onboarding/quiz': typeof AuthenticatedOnboardingQuizRouteRoute
  '/onboarding/review': typeof AuthenticatedOnboardingReviewRouteRoute
  '/onboarding/speed-dating': typeof AuthenticatedOnboardingSpeedDatingRouteRoute
  '/personas/create': typeof AuthenticatedPersonasCreateRouteRoute
  '/personas/me': typeof AuthenticatedPersonasMeRouteRoute
  '/personas/quiz': typeof AuthenticatedPersonasQuizRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/login': typeof LoginRouteRoute
  '/register': typeof RegisterRouteRoute
  '/signup': typeof SignupRouteRoute
  '/speed-dating': typeof SpeedDatingRouteRoute
  '/chat': typeof AuthenticatedChatRouteRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRoute
  '/onboarding/profile': typeof AuthenticatedOnboardingProfileRouteRoute
  '/onboarding/quiz': typeof AuthenticatedOnboardingQuizRouteRoute
  '/onboarding/review': typeof AuthenticatedOnboardingReviewRouteRoute
  '/onboarding/speed-dating': typeof AuthenticatedOnboardingSpeedDatingRouteRoute
  '/personas/create': typeof AuthenticatedPersonasCreateRouteRoute
  '/personas/me': typeof AuthenticatedPersonasMeRouteRoute
  '/personas/quiz': typeof AuthenticatedPersonasQuizRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/register': typeof RegisterRouteRoute
  '/signup': typeof SignupRouteRoute
  '/speed-dating': typeof SpeedDatingRouteRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRoute
  '/_authenticated/onboarding/profile': typeof AuthenticatedOnboardingProfileRouteRoute
  '/_authenticated/onboarding/quiz': typeof AuthenticatedOnboardingQuizRouteRoute
  '/_authenticated/onboarding/review': typeof AuthenticatedOnboardingReviewRouteRoute
  '/_authenticated/onboarding/speed-dating': typeof AuthenticatedOnboardingSpeedDatingRouteRoute
  '/_authenticated/personas/create': typeof AuthenticatedPersonasCreateRouteRoute
  '/_authenticated/personas/me': typeof AuthenticatedPersonasMeRouteRoute
  '/_authenticated/personas/quiz': typeof AuthenticatedPersonasQuizRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/signup'
    | '/speed-dating'
    | '/chat'
    | '/onboarding'
    | '/settings'
    | '/onboarding/profile'
    | '/onboarding/quiz'
    | '/onboarding/review'
    | '/onboarding/speed-dating'
    | '/personas/create'
    | '/personas/me'
    | '/personas/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/signup'
    | '/speed-dating'
    | '/chat'
    | '/onboarding'
    | '/settings'
    | '/onboarding/profile'
    | '/onboarding/quiz'
    | '/onboarding/review'
    | '/onboarding/speed-dating'
    | '/personas/create'
    | '/personas/me'
    | '/personas/quiz'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/signup'
    | '/speed-dating'
    | '/_authenticated/chat'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/onboarding/profile'
    | '/_authenticated/onboarding/quiz'
    | '/_authenticated/onboarding/review'
    | '/_authenticated/onboarding/speed-dating'
    | '/_authenticated/personas/create'
    | '/_authenticated/personas/me'
    | '/_authenticated/personas/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
  RegisterRouteRoute: typeof RegisterRouteRoute
  SignupRouteRoute: typeof SignupRouteRoute
  SpeedDatingRouteRoute: typeof SpeedDatingRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speed-dating': {
      id: '/speed-dating'
      path: '/speed-dating'
      fullPath: '/speed-dating'
      preLoaderRoute: typeof SpeedDatingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personas/quiz': {
      id: '/_authenticated/personas/quiz'
      path: '/personas/quiz'
      fullPath: '/personas/quiz'
      preLoaderRoute: typeof AuthenticatedPersonasQuizRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personas/me': {
      id: '/_authenticated/personas/me'
      path: '/personas/me'
      fullPath: '/personas/me'
      preLoaderRoute: typeof AuthenticatedPersonasMeRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personas/create': {
      id: '/_authenticated/personas/create'
      path: '/personas/create'
      fullPath: '/personas/create'
      preLoaderRoute: typeof AuthenticatedPersonasCreateRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/speed-dating': {
      id: '/_authenticated/onboarding/speed-dating'
      path: '/speed-dating'
      fullPath: '/onboarding/speed-dating'
      preLoaderRoute: typeof AuthenticatedOnboardingSpeedDatingRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/review': {
      id: '/_authenticated/onboarding/review'
      path: '/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof AuthenticatedOnboardingReviewRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/quiz': {
      id: '/_authenticated/onboarding/quiz'
      path: '/quiz'
      fullPath: '/onboarding/quiz'
      preLoaderRoute: typeof AuthenticatedOnboardingQuizRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/profile': {
      id: '/_authenticated/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof AuthenticatedOnboardingProfileRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
  }
}

interface AuthenticatedOnboardingRouteRouteChildren {
  AuthenticatedOnboardingProfileRouteRoute: typeof AuthenticatedOnboardingProfileRouteRoute
  AuthenticatedOnboardingQuizRouteRoute: typeof AuthenticatedOnboardingQuizRouteRoute
  AuthenticatedOnboardingReviewRouteRoute: typeof AuthenticatedOnboardingReviewRouteRoute
  AuthenticatedOnboardingSpeedDatingRouteRoute: typeof AuthenticatedOnboardingSpeedDatingRouteRoute
}

const AuthenticatedOnboardingRouteRouteChildren: AuthenticatedOnboardingRouteRouteChildren =
  {
    AuthenticatedOnboardingProfileRouteRoute:
      AuthenticatedOnboardingProfileRouteRoute,
    AuthenticatedOnboardingQuizRouteRoute:
      AuthenticatedOnboardingQuizRouteRoute,
    AuthenticatedOnboardingReviewRouteRoute:
      AuthenticatedOnboardingReviewRouteRoute,
    AuthenticatedOnboardingSpeedDatingRouteRoute:
      AuthenticatedOnboardingSpeedDatingRouteRoute,
  }

const AuthenticatedOnboardingRouteRouteWithChildren =
  AuthenticatedOnboardingRouteRoute._addFileChildren(
    AuthenticatedOnboardingRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRouteRoute: typeof AuthenticatedChatRouteRoute
  AuthenticatedOnboardingRouteRoute: typeof AuthenticatedOnboardingRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRoute
  AuthenticatedPersonasCreateRouteRoute: typeof AuthenticatedPersonasCreateRouteRoute
  AuthenticatedPersonasMeRouteRoute: typeof AuthenticatedPersonasMeRouteRoute
  AuthenticatedPersonasQuizRouteRoute: typeof AuthenticatedPersonasQuizRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRouteRoute: AuthenticatedChatRouteRoute,
  AuthenticatedOnboardingRouteRoute:
    AuthenticatedOnboardingRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRoute,
  AuthenticatedPersonasCreateRouteRoute: AuthenticatedPersonasCreateRouteRoute,
  AuthenticatedPersonasMeRouteRoute: AuthenticatedPersonasMeRouteRoute,
  AuthenticatedPersonasQuizRouteRoute: AuthenticatedPersonasQuizRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
  RegisterRouteRoute: RegisterRouteRoute,
  SignupRouteRoute: SignupRouteRoute,
  SpeedDatingRouteRoute: SpeedDatingRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
