/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeedDatingRouteRouteImport } from './routes/speed-dating/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'

const SpeedDatingRouteRoute = SpeedDatingRouteRouteImport.update({
  id: '/speed-dating',
  path: '/speed-dating',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/speed-dating': typeof SpeedDatingRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/speed-dating': typeof SpeedDatingRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/speed-dating': typeof SpeedDatingRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/speed-dating'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/speed-dating'
  id: '__root__' | '/' | '/speed-dating'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  SpeedDatingRouteRoute: typeof SpeedDatingRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speed-dating': {
      id: '/speed-dating'
      path: '/speed-dating'
      fullPath: '/speed-dating'
      preLoaderRoute: typeof SpeedDatingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  SpeedDatingRouteRoute: SpeedDatingRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
